# Generated by Django 5.1.7 on 2025-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='arquivada',
            field=models.BooleanField(default=False),
        ),
    ]
